# SwiftLint Configuration for KeyPath
# Focuses on critical issues while allowing reasonable flexibility

# Exclude build artifacts and generated code
excluded:
  - .build
  - dist
  - Tests/InstallationWizardTests.disabled
  - "*.generated.swift"
  - peekaboo  # Exclude nested peekaboo project

# Configure rules - make everything warnings for CI
line_length:
  error: 500      # Extremely generous - almost never error
  warning: 200    # Reasonable warning threshold
  ignores_urls: true
  ignores_function_declarations: true
  ignores_comments: true

identifier_name:
  min_length:
    error: 1      # Allow single character names
    warning: 1    # Only warn for single characters
  max_length:
    error: 100    # Very generous max length
    warning: 40   # Reasonable warning threshold
  excluded:
    - id          # Allow common short names
    - x
    - y
    - i           # Allow loop counters
    - j
    - k
    - m
    - n
    - p
    - rx
  allowed_symbols: ["_"]  # Allow underscores in names

# Disable problematic rules for CI
disabled_rules:
  - type_body_length
  - file_length
  - function_body_length
  - cyclomatic_complexity
  - large_tuple
  - function_parameter_count
  - force_try           # Allow force try in tests
  - force_cast          # Allow force cast in tests
  - force_unwrapping    # Allow force unwrapping in tests

# Custom reporter for CI
reporter: "github-actions-logging"

# Custom rules
custom_rules:
  # Flag direct Process() usage outside SubprocessRunner
  # All subprocess execution should go through SubprocessRunner.shared to prevent MainActor blocking
  no_direct_process:
    name: "Direct Process() Usage"
    regex: '\bProcess\s*\('
    message: "Direct Process() usage detected. Use SubprocessRunner.shared.run() instead to prevent MainActor blocking."
    severity: warning
    excluded:
      - "**/SubprocessRunner.swift"  # Allow Process() in SubprocessRunner itself
      - "**/SubprocessRunnerFake.swift"  # Allow Process() in test fakes
      - "**/*Test*.swift"  # Allow Process() in tests (they may need to test Process directly)
      - "Sources/**/ProcessLifecycleManager.swift"  # Legacy lifecycle utility (monitored separately)
      - "dev-tools/**"  # Allow Process() in dev tools

  # Modern SwiftUI best practices (from Hacking with Swift article)
  # https://www.hackingwithswift.com/articles/281/what-to-fix-in-ai-generated-swift-code

  no_foreground_color:
    name: "Deprecated foregroundColor"
    regex: '\.foregroundColor\s*\('
    message: "Use .foregroundStyle() instead of deprecated .foregroundColor()"
    severity: warning
    excluded:
      - "dev-tools/**"  # Dev tools may use legacy APIs

  no_corner_radius:
    name: "Deprecated cornerRadius"
    regex: '\.cornerRadius\s*\('
    message: "Use .clipShape(.rect(cornerRadius:)) instead of deprecated .cornerRadius()"
    severity: warning

  no_navigation_view:
    name: "Deprecated NavigationView"
    regex: '\bNavigationView\s*\{'
    message: "Use NavigationStack instead of deprecated NavigationView"
    severity: warning

  no_task_sleep_nanoseconds:
    name: "Old Task.sleep API"
    regex: 'Task\.sleep\s*\(\s*nanoseconds\s*:'
    message: "Use Task.sleep(for: .seconds()) instead of nanoseconds"
    severity: warning

  no_array_enumerated:
    name: "Array(enumerated()) anti-pattern"
    regex: 'Array\s*\(\s*\w+\.enumerated\s*\(\s*\)\s*\)'
    message: "Use .indices or direct ForEach with id: instead of Array(enumerated())"
    severity: warning