#!/bin/bash

echo "=== Manual Cleanup Required ==="
echo "Please run these commands manually to clean up old KeyPath services:"
echo ""
echo "# 1. Remove the old LaunchDaemon plist file:"
echo "sudo rm -f /Library/LaunchDaemons/com.keypath.kanata.plist"
echo ""
echo "# 2. Disable and remove old services:"
echo "sudo launchctl bootout system/com.keypath.helper"
echo "sudo launchctl bootout system/com.keypath.kanata"
echo "sudo launchctl bootout system/com.keypath.kanata.helper"
echo "sudo launchctl bootout system/com.keypath.kanata.xpc"
echo ""
echo "# 3. Check if any SMAppService registrations need cleanup:"
echo "# (These might require app-specific cleanup through the registered apps)"
echo ""
echo "# 4. Verify cleanup:"
echo "launchctl print system | grep keypath"
echo ""
echo "After running these commands, the old conflicting services should be removed."