@testable import KeyPathAppKit
@preconcurrency import XCTest

@MainActor
final class KanataManagerResetTests: XCTestCase {
    func testResetWritesDefaultConfig() async throws {
        // Given a fresh manager
        let manager = RuntimeCoordinator()

        // When: reset to default config
        try await manager.resetToDefaultConfig()

        // Then: the default config file should exist and be a valid Kanata config
        let path = NSHomeDirectory() + "/.config/keypath/keypath.kbd"
        let written = try String(contentsOfFile: path, encoding: .utf8)

        // Verify the file was written and contains essential elements
        XCTAssertFalse(written.isEmpty, "Config file should not be empty")
        XCTAssertTrue(
            written.contains(";; Generated by KeyPath"),
            "Config should have KeyPath header"
        )
        XCTAssertTrue(
            written.contains("defcfg"),
            "Config should contain defcfg block"
        )
        XCTAssertTrue(
            written.contains("defsrc"),
            "Config should contain defsrc block"
        )
        XCTAssertTrue(
            written.contains("deflayer"),
            "Config should contain deflayer block"
        )

        // The config should have the macOS function keys collection enabled by default
        // These are the F-key mappings that preserve brightness/volume controls
        XCTAssertTrue(
            written.contains("brdn") || written.contains("brup") || written.contains("mute"),
            "Config should contain macOS function key mappings"
        )
    }
}
