#!/bin/bash
#
# dev-setup-sudoers.sh - Configure sudoers for KeyPath development testing
#
# This script adds NOPASSWD rules for the current user to run privileged
# commands needed for testing without password prompts or osascript dialogs.
#
# ⚠️  WARNING: This is for LOCAL DEVELOPMENT ONLY!
# ⚠️  DO NOT ship this configuration to end users!
# ⚠️  Run dev-remove-sudoers.sh before making public releases.
#
# Usage:
#   sudo ./Scripts/dev-setup-sudoers.sh
#
# What it does:
#   - Creates /etc/sudoers.d/keypath-dev with NOPASSWD rules
#   - Allows launchctl, mkdir, cp, rm for KeyPath-specific paths only
#   - Verifies syntax before installing (visudo -c)
#
# To remove:
#   sudo ./Scripts/dev-remove-sudoers.sh
#

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Configuration
SUDOERS_FILE="/etc/sudoers.d/keypath-dev"
CURRENT_USER="${SUDO_USER:-$(whoami)}"

echo "=================================================="
echo "KeyPath Development Sudoers Setup"
echo "=================================================="
echo ""

# Check if running as root
if [ "$(id -u)" -ne 0 ]; then
    echo -e "${RED}Error: This script must be run with sudo${NC}"
    echo "Usage: sudo $0"
    exit 1
fi

# Check if already installed
if [ -f "$SUDOERS_FILE" ]; then
    echo -e "${YELLOW}Warning: $SUDOERS_FILE already exists${NC}"
    echo "Current contents:"
    cat "$SUDOERS_FILE"
    echo ""
    read -p "Do you want to replace it? (y/N) " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "Aborted."
        exit 0
    fi
fi

echo "Creating sudoers rules for user: $CURRENT_USER"
echo ""

# Create the sudoers file content
# NOTE: Rules are scoped to KeyPath-specific paths only for security
SUDOERS_CONTENT="# KeyPath Development Testing - NOPASSWD rules
# Generated by: Scripts/dev-setup-sudoers.sh
# User: $CURRENT_USER
# Date: $(date)
#
# WARNING: This is for LOCAL DEVELOPMENT ONLY!
# Remove before shipping: sudo ./Scripts/dev-remove-sudoers.sh

# launchctl commands (for managing LaunchDaemons)
$CURRENT_USER ALL=(root) NOPASSWD: /bin/launchctl bootstrap system /Library/LaunchDaemons/com.keypath.*
$CURRENT_USER ALL=(root) NOPASSWD: /bin/launchctl bootout system/com.keypath.*
$CURRENT_USER ALL=(root) NOPASSWD: /bin/launchctl enable system/com.keypath.*
$CURRENT_USER ALL=(root) NOPASSWD: /bin/launchctl disable system/com.keypath.*
$CURRENT_USER ALL=(root) NOPASSWD: /bin/launchctl kickstart -k system/com.keypath.*
$CURRENT_USER ALL=(root) NOPASSWD: /bin/launchctl kill SIGTERM system/com.keypath.*
$CURRENT_USER ALL=(root) NOPASSWD: /bin/launchctl print system/com.keypath.*
$CURRENT_USER ALL=(root) NOPASSWD: /bin/launchctl list com.keypath.*

# Directory creation for KeyPath
$CURRENT_USER ALL=(root) NOPASSWD: /bin/mkdir -p /Library/KeyPath
$CURRENT_USER ALL=(root) NOPASSWD: /bin/mkdir -p /Library/KeyPath/*

# File operations for KeyPath binaries and config
$CURRENT_USER ALL=(root) NOPASSWD: /bin/cp * /Library/KeyPath/*
$CURRENT_USER ALL=(root) NOPASSWD: /bin/cp * /Library/LaunchDaemons/com.keypath.*
$CURRENT_USER ALL=(root) NOPASSWD: /bin/rm -f /Library/KeyPath/*
$CURRENT_USER ALL=(root) NOPASSWD: /bin/rm -rf /Library/KeyPath
$CURRENT_USER ALL=(root) NOPASSWD: /bin/rm -f /Library/LaunchDaemons/com.keypath.*

# Chmod/chown for KeyPath paths
$CURRENT_USER ALL=(root) NOPASSWD: /bin/chmod * /Library/KeyPath/*
$CURRENT_USER ALL=(root) NOPASSWD: /usr/sbin/chown * /Library/KeyPath/*

# Kill processes (needed for process management)
$CURRENT_USER ALL=(root) NOPASSWD: /bin/kill -9 *
$CURRENT_USER ALL=(root) NOPASSWD: /bin/kill -15 *
"

# Write to a temp file first for validation
TEMP_FILE=$(mktemp)
echo "$SUDOERS_CONTENT" > "$TEMP_FILE"

# Validate syntax with visudo
echo "Validating sudoers syntax..."
if ! visudo -c -f "$TEMP_FILE" 2>/dev/null; then
    echo -e "${RED}Error: Invalid sudoers syntax${NC}"
    rm "$TEMP_FILE"
    exit 1
fi

echo -e "${GREEN}Syntax OK${NC}"
echo ""

# Install the file
echo "Installing to $SUDOERS_FILE..."
cp "$TEMP_FILE" "$SUDOERS_FILE"
chmod 440 "$SUDOERS_FILE"
rm "$TEMP_FILE"

echo ""
echo -e "${GREEN}✅ Sudoers configuration installed successfully!${NC}"
echo ""
echo "You can now run tests with privileged operations:"
echo "  KEYPATH_USE_SUDO=1 swift test"
echo ""
echo "To verify the setup works:"
echo "  sudo -n /bin/launchctl list com.keypath.kanata 2>/dev/null && echo 'sudo works without password'"
echo ""
echo -e "${YELLOW}⚠️  Remember to remove before public release:${NC}"
echo "  sudo ./Scripts/dev-remove-sudoers.sh"
echo ""
