#!/usr/bin/env bash
set -euo pipefail

APP_PATH="${APP_PATH:-/Applications/KeyPath.app}"
CLI="${KEYPATH_CLI:-$APP_PATH/Contents/MacOS/keypath-cli}"
CONFIG_DIR="${KEYPATH_CONFIG_DIR:-$HOME/.config/keypath}"
CONFIG_PATH="$CONFIG_DIR/keypath.kbd"
CONFIG_REAL_DIR="$(python3 -c 'import os, sys; print(os.path.realpath(sys.argv[1]))' "$CONFIG_DIR")"
KANATA_BIN="${KEYPATH_KANATA_BIN:-$APP_PATH/Contents/Library/KeyPath/Kanata Engine.app/Contents/MacOS/kanata}"
TCP_HOST="${KEYPATH_TCP_HOST:-127.0.0.1}"
TCP_PORT="${KEYPATH_TCP_PORT:-37001}"
TCP_TIMEOUT_SECONDS="${KEYPATH_TCP_TIMEOUT_SECONDS:-20}"
RUN_LOG_GATE="${KEYPATH_QA_RUN_LOG_GATE:-1}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

TMP_DIR="$(mktemp -d)"
BACKUP_DIR="$TMP_DIR/original-keypath-config"
CONFIG_EXISTED=0
START_EPOCH="$(date +%s)"

cleanup() {
  local status=$?
  set +e
  if [[ "$CONFIG_EXISTED" == "1" ]]; then
    mkdir -p "$CONFIG_REAL_DIR"
    find "$CONFIG_REAL_DIR" -mindepth 1 -maxdepth 1 -exec rm -rf {} +
    cp -a "$BACKUP_DIR"/. "$CONFIG_REAL_DIR"/
  else
    rm -rf "$CONFIG_REAL_DIR"
  fi
  if [[ -x "$CLI" && "$CONFIG_EXISTED" == "1" ]]; then
    "$CLI" config apply --json --quiet >/dev/null 2>&1 || "$CLI" service reload --json --quiet >/dev/null 2>&1 || true
  fi
  rm -rf "$TMP_DIR"
  exit "$status"
}
trap cleanup EXIT

require_executable() {
  if [[ ! -x "$1" ]]; then
    echo "error: required executable not found: $1" >&2
    exit 1
  fi
}

assert_contains() {
  local haystack="$1"
  local needle="$2"
  local label="$3"
  if [[ "$haystack" != *"$needle"* ]]; then
    echo "error: $label did not contain expected snippet:" >&2
    echo "  $needle" >&2
    exit 1
  fi
}

wait_for_tcp() {
  local probe="$TMP_DIR/tcp-probe.log"
  local deadline=$((SECONDS + TCP_TIMEOUT_SECONDS))
  while true; do
    if nc -vz -w 1 "$TCP_HOST" "$TCP_PORT" >"$probe" 2>&1; then
      return 0
    fi
    if (( SECONDS >= deadline )); then
      cat "$probe" >&2 || true
      echo "error: TCP did not become ready at ${TCP_HOST}:${TCP_PORT}" >&2
      exit 1
    fi
    sleep 1
  done
}

apply_and_verify() {
  local label="$1"
  echo "==> $label"
  "$CLI" config apply --json --quiet >/dev/null
  "$CLI" config check --json --quiet >/dev/null
  if [[ ! -f "$CONFIG_PATH" ]]; then
    echo "error: generated config missing: $CONFIG_PATH" >&2
    exit 1
  fi
  (cd "$CONFIG_DIR" && "$KANATA_BIN" --cfg "$(basename "$CONFIG_PATH")" --check >/dev/null)
  "$CLI" service reload --json --quiet >/dev/null
  wait_for_tcp
}

write_app_specific_fixture() {
  python3 - "$CONFIG_DIR" <<'PY'
import json
import sys
from pathlib import Path

config_dir = Path(sys.argv[1])
config_dir.mkdir(parents=True, exist_ok=True)
timestamp = "2026-01-01T00:00:00Z"
keymaps = [
    {
        "id": "71000000-0000-0000-0000-000000000001",
        "mapping": {
            "id": "71000000-0000-0000-0000-000000000002",
            "bundleIdentifier": "com.apple.Safari",
            "displayName": "Safari",
            "virtualKeyName": "vk_safari",
            "createdAt": timestamp,
            "modifiedAt": timestamp,
            "isEnabled": True,
        },
        "overrides": [
            {
                "id": "71000000-0000-0000-0000-000000000003",
                "inputKey": "j",
                "action": {"keystroke": {"key": "down"}},
                "description": "QA smoke app-specific down",
            },
            {
                "id": "71000000-0000-0000-0000-000000000004",
                "inputKey": "k",
                "action": {"keystroke": {"key": "up"}},
                "description": "QA smoke app-specific up",
            },
        ],
    }
]
(config_dir / "AppKeymaps.json").write_text(json.dumps(keymaps, indent=2, sort_keys=True) + "\n")
(config_dir / "keypath-apps.kbd").write_text(
    """;; Generated by KeyPath release QA smoke
(defvirtualkeys
  vk_safari XX
)

(defalias
  kp-j (switch ((input virtual vk_safari)) down break () j break)
  kp-k (switch ((input virtual vk_safari)) up break () k break)
)
""",
    encoding="utf-8",
)
PY
}

prepare_custom_rule_fixtures() {
  mkdir -p "$CONFIG_DIR"
  printf '[]\n' >"$CONFIG_DIR/CustomRules.json"

  "$CLI" rule add z x --on-conflict replace --json --quiet >/dev/null
  "$CLI" rule add q --tap q --hold lctl --tap-timeout 180 --on-conflict replace --json --quiet >/dev/null
  "$CLI" rule add grave --action '{"hyper":{}}' --on-conflict replace --json --quiet >/dev/null
  "$CLI" rule add f13 f14 --on-conflict replace --json --quiet >/dev/null
  "$CLI" rule add v --action '{"launchApp":{"name":"TextEdit","bundleId":"com.apple.TextEdit"}}' --on-conflict replace --json --quiet >/dev/null
  "$CLI" rule add b --action '{"openURL":{"_0":"https://example.com"}}' --on-conflict replace --json --quiet >/dev/null
  "$CLI" rule add n --action '{"systemAction":{"id":"mission-control"}}' --on-conflict replace --json --quiet >/dev/null
  "$CLI" rule add m --action '{"windowAction":{"position":"left"}}' --on-conflict replace --json --quiet >/dev/null
  "$CLI" rule add slash --action '{"activateLayer":{"name":"nav"}}' --on-conflict replace --json --quiet >/dev/null
  "$CLI" rule add comma --action '{"keystroke":{"key":"comma"}}' --behavior '{"macro":{"outputs":[],"text":"qa","source":"text"}}' --on-conflict replace --json --quiet >/dev/null
}

prepare_collection_fixtures() {
  python3 - "$CONFIG_DIR/RuleCollections.json" <<'PY'
import json
import sys
from pathlib import Path

path = Path(sys.argv[1])
if path.exists():
    payload = json.loads(path.read_text())
else:
    payload = {"collections": []}
collections = payload.setdefault("collections", [])
if not isinstance(collections, list):
    raise SystemExit("RuleCollections.json does not contain a collections array")

qa_ids = {
    "80000000-0000-0000-0000-000000000001",
    "80000000-0000-0000-0000-000000000002",
    "80000000-0000-0000-0000-000000000003",
    "80000000-0000-0000-0000-000000000004",
}
collections[:] = [c for c in collections if c.get("id") not in qa_ids and not str(c.get("name", "")).startswith("QA Smoke ")]
for collection in collections:
    collection["isEnabled"] = False

def collection(id_, name, summary, category, configuration, target_layer="base", mappings=None, momentary=None):
    item = {
        "id": id_,
        "name": name,
        "summary": summary,
        "category": category,
        "icon": "testtube.2",
        "tags": ["release-qa"],
        "isEnabled": True,
        "isSystemDefault": False,
        "mappings": mappings or [],
        "targetLayer": target_layer,
        "activationHint": None,
        "configuration": configuration,
    }
    if momentary is not None:
        item["momentaryActivator"] = momentary
    return item

timing = {
    "tapWindow": 200,
    "holdDelay": 150,
    "quickTapEnabled": False,
    "quickTapTermMs": 0,
    "tapOffsets": {},
    "holdOffsets": {},
    "requirePriorIdleMs": 150,
}

collections.extend([
    collection(
        "80000000-0000-0000-0000-000000000001",
        "QA Smoke Home Row Mod",
        "Release QA home row modifier fixture",
        "custom",
        {
            "type": "homeRowMods",
            "enabledKeys": ["a"],
            "modifierAssignments": {"a": "lsft"},
            "layerAssignments": {"a": "nav"},
            "holdMode": "modifiers",
            "hasUserSelectedHoldMode": True,
            "layerToggleMode": "whileHeld",
            "timing": timing,
            "keySelection": "custom",
            "showAdvanced": True,
            "timingMode": "precision",
            "showExpertTiming": True,
            "oppositeHandMode": "off",
        },
    ),
    collection(
        "80000000-0000-0000-0000-000000000002",
        "QA Smoke Home Row Layer",
        "Release QA home row layer fixture",
        "layers",
        {
            "type": "homeRowLayerToggles",
            "enabledKeys": ["f"],
            "layerAssignments": {"f": "nav"},
            "timing": timing,
            "keySelection": "custom",
            "toggleMode": "whileHeld",
            "showAdvanced": True,
            "oppositeHandMode": "off",
        },
    ),
    collection(
        "80000000-0000-0000-0000-000000000003",
        "QA Smoke Chords",
        "Release QA chord fixture",
        "custom",
        {
            "type": "chordGroups",
            "groups": [
                {
                    "id": "81000000-0000-0000-0000-000000000001",
                    "name": "QAChords",
                    "timeout": 250,
                    "chords": [
                        {
                            "id": "81000000-0000-0000-0000-000000000002",
                            "keys": ["s", "d"],
                            "action": {"keystroke": {"key": "esc"}},
                            "description": "QA smoke chord escape",
                            "isEnabled": True,
                        }
                    ],
                    "description": "Release QA chord group",
                    "category": "navigation",
                }
            ],
            "activeGroupID": "81000000-0000-0000-0000-000000000001",
            "showAdvanced": True,
        },
    ),
    collection(
        "80000000-0000-0000-0000-000000000004",
        "QA Smoke Launcher",
        "Release QA launcher fixture",
        "productivity",
        {
            "type": "launcherGrid",
            "activationMode": "holdHyper",
            "hyperTriggerMode": "hold",
            "mappings": [
                {
                    "id": "82000000-0000-0000-0000-000000000001",
                    "key": "o",
                    "action": {"openURL": {"_0": "https://example.com"}},
                    "isEnabled": True,
                    "userDescription": "QA smoke URL",
                },
                {
                    "id": "82000000-0000-0000-0000-000000000002",
                    "key": "p",
                    "action": {"launchApp": {"name": "TextEdit", "bundleId": "com.apple.TextEdit"}},
                    "isEnabled": True,
                    "userDescription": "QA smoke app launch",
                },
            ],
            "hasSeenWelcome": True,
        },
        target_layer="qa-launcher",
        momentary={"input": "h", "targetLayer": "qa-launcher", "sourceLayer": "base"},
    ),
])

path.parent.mkdir(parents=True, exist_ok=True)
path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n")
PY
}

require_executable "$CLI"
require_executable "$KANATA_BIN"

if [[ -d "$CONFIG_REAL_DIR" ]]; then
  CONFIG_EXISTED=1
  mkdir -p "$BACKUP_DIR"
  cp -a "$CONFIG_REAL_DIR"/. "$BACKUP_DIR"/
fi
mkdir -p "$CONFIG_DIR"

"$CLI" --version >/dev/null
"$CLI" service status --json --quiet >/dev/null
wait_for_tcp

write_app_specific_fixture
prepare_custom_rule_fixtures
apply_and_verify "custom rule families, app-specific aliases, and bundled Kanata validation"

config="$("$CLI" config show --no-json --quiet)"
assert_contains "$config" "z x" "simple remap config"
assert_contains "$config" "tap-hold" "tap-hold config"
assert_contains "$config" "(multi lctl lmet lalt lsft)" "hyper modifier config"
assert_contains "$config" "f13" "function key config source"
assert_contains "$config" "f14" "function key config output"
assert_contains "$config" 'push-msg "launch:com.apple.TextEdit"' "launcher/app action config"
assert_contains "$config" 'push-msg "open:' "URL action config"
assert_contains "$config" 'push-msg "system:mission-control"' "system action config"
assert_contains "$config" 'push-msg "window:left"' "window action config"
assert_contains "$config" "(layer-switch nav)" "layer action config"
assert_contains "$config" "(macro q a)" "text macro config"
assert_contains "$config" "(include keypath-apps.kbd)" "app-specific include config"
assert_contains "$config" "@kp-j" "app-specific base alias config"

prepare_collection_fixtures
apply_and_verify "home-row, layer, chord, and launcher collection families"

config="$("$CLI" config show --no-json --quiet)"
assert_contains "$config" "beh_base_a" "home row mod config"
assert_contains "$config" "(layer-while-held nav)" "home row layer config"
assert_contains "$config" "(defchords QAChords" "chord group config"
assert_contains "$config" "(chord QAChords s)" "chord participation config"
assert_contains "$config" "qa-launcher" "launcher layer config"
assert_contains "$config" 'push-msg "launch:com.apple.TextEdit"' "launcher collection app action config"

if [[ "$RUN_LOG_GATE" == "1" ]]; then
  KEYPATH_QA_SINCE_EPOCH="$START_EPOCH" "$SCRIPT_DIR/qa-keypath-log-gate.sh"
fi

echo "KeyPath installed-app release smoke passed. Original config will be restored."
