import Foundation
import KeyPathCore
import KeyPathDaemonLifecycle
import Network

// MARK: - Kanata Configuration Model

/// Represents Kanata configuration data and metadata
public struct KanataConfiguration: Sendable {
    public let content: String
    public let keyMappings: [KeyMapping]
    public let lastModified: Date
    public let path: String
    public let chordGroups: [ChordGroupConfig]
    public let sequences: [KanataDefseqParser.ParsedSequence]

    public init(
        content: String,
        keyMappings: [KeyMapping],
        lastModified: Date,
        path: String,
        chordGroups: [ChordGroupConfig] = [],
        sequences: [KanataDefseqParser.ParsedSequence] = []
    ) {
        self.content = content
        self.keyMappings = keyMappings
        self.lastModified = lastModified
        self.path = path
        self.chordGroups = chordGroups
        self.sequences = sequences
    }

    /// Generate configuration content from key mappings (adds default system collections when absent).
    public static func generateFromMappings(_ mappings: [KeyMapping]) -> String {
        let collections = [RuleCollection].collection(named: "Custom Mappings", mappings: mappings)
        return generateFromCollections(collections)
    }

    /// Generate configuration content from rule collections.
    /// Flattens enabled collections to `defsrc`/`deflayer` for backward compatibility with Kanata config format.
    public static func generateFromCollections(
        _ collections: [RuleCollection],
        leaderKeyPreference: LeaderKeyPreference? = nil,
        navActivationMode: ContextHUDTriggerMode = .tapToToggle,
        chordGroups: [ChordGroupConfig] = [],
        sequences: [KanataDefseqParser.ParsedSequence] = []
    ) -> String {
        var resolvedCollections = collections.isEmpty ? defaultSystemCollections : collections
        if !resolvedCollections.contains(where: { $0.id == RuleCollectionIdentifier.macFunctionKeys }) {
            resolvedCollections.append(contentsOf: defaultSystemCollections)
        }
        resolvedCollections = RuleCollectionDeduplicator.dedupe(resolvedCollections)
        let enabledCollections = resolvedCollections.filter(\.isEnabled)
        // Note: Disabled collections are NOT written to config (ADR-025: JSON stores are source of truth)

        // Extract UI-authored chord groups config (MAL-37)
        let uiChordGroupsConfig = enabledCollections
            .compactMap(\.configuration.chordGroupsConfig)
            .first

        AppLogger.shared.log("📚 [KanataConfig] Enabled collections: \(enabledCollections.map { "\($0.name) (enabled: \($0.isEnabled))" }.joined(separator: ", "))")

        let (rawBlocks, aliasDefinitions, extraLayers, chordMappings) = buildCollectionBlocks(
            from: enabledCollections,
            leaderKeyPreference: leaderKeyPreference,
            navActivationMode: navActivationMode
        )
        let mergedAliasDefinitions = aliasDefinitions
        AppLogger.shared.log("📚 [KanataConfig] Total alias definitions: \(mergedAliasDefinitions.count), first 5: \(mergedAliasDefinitions.prefix(5).map(\.aliasName).joined(separator: ", "))")
        let blocks = deduplicateBlocks(rawBlocks)
        let enabledNames = enabledCollections.map(\.name).joined(separator: ", ")

        let macosDeviceExclusions = renderMacOSDeviceExclusionsForDefcfg()
        let header = """
        ;; Generated by KeyPath
        ;; Enabled: \(enabledNames.isEmpty ? "none" : enabledNames)

        (defcfg
          process-unmapped-keys yes
          danger-enable-cmd yes
        """ + macosDeviceExclusions + """
        )
        """

        let safetyNotes = """
        ;; SAFETY: This configuration is auto-generated. Do not edit by hand.
        ;; SAFETY: Only explicitly enabled mappings are written to this file.
        ;; EMERGENCY EXIT: Hold Left Control + Space + Escape to force-quit Kanata
        """

        let defvarBlock = renderDefvarBlock()
        let sourceBlock = renderDefsrcBlock(blocks)

        // Load app-specific keys to use @kp-{key} aliases in base layer
        let appSpecificKeys = loadAppSpecificKeys()

        let baseLayerBlock = renderLayerBlock(name: RuleCollectionLayer.base.kanataName, blocks: blocks) { entry in
            // If this key has app-specific overrides, use the alias instead of the plain key
            // This enables the switch expression in keypath-apps.kbd to intercept the key
            let keyName = entry.sourceKey.lowercased()
            if appSpecificKeys.contains(keyName) {
                return appSpecificAliasName(for: keyName)
            }
            return entry.baseOutput
        }
        let additionalLayerBlocks = extraLayers.map { layer in
            renderLayerBlock(name: layer.kanataName, blocks: blocks) { entry in
                entry.layerOutputs[layer] ?? "_"
            }
        }.joined(separator: "\n")
        let fakeKeysBlock = renderFakeKeysBlock(extraLayers)
        let aliasBlock = renderAliasBlock(mergedAliasDefinitions)
        let chordsBlock = renderChordsBlock(chordMappings)
        let preservedChordGroupsBlock = renderChordGroupsBlock(chordGroups)
        let preservedSequencesBlock = renderSequencesBlock(sequences)
        let uiChordGroupsBlock = renderUIChordGroupsBlock(uiChordGroupsConfig)

        // Include keypath-apps.kbd if there are app-specific keys
        // This must come after defcfg but before any layer that uses @kp-* aliases
        let appIncludeBlock = if !appSpecificKeys.isEmpty {
            """
            ;; App-specific keymaps (virtual keys and switch expressions)
            (include keypath-apps.kbd)
            """
        } else {
            ""
        }

        return [
            header,
            safetyNotes,
            appIncludeBlock,
            defvarBlock,
            sourceBlock,
            aliasBlock, // Must come before layers that reference aliases (e.g., @kp-ac-spc)
            baseLayerBlock,
            additionalLayerBlocks,
            fakeKeysBlock,
            chordsBlock,
            preservedSequencesBlock,
            preservedChordGroupsBlock,
            uiChordGroupsBlock
        ]
        .filter { !$0.isEmpty }
        .joined(separator: "\n")
    }

    private static let defaultEmptyConfig = generateFromCollections(defaultSystemCollections)

    // MARK: - macOS Device Selection (VirtualHID loop prevention)

    /// On macOS, Kanata may try to intercept *all* keyboards, including the VirtualHID output keyboard.
    /// If it grabs the VirtualHID device, it can create feedback loops (especially with symmetric remaps like 1<->2).
    /// We exclude VirtualHID keyboards that `kanata --list` reports.
    private static func renderMacOSDeviceExclusionsForDefcfg() -> String {
        #if os(macOS)
            let devices = detectMacOSVirtualHIDDevicesForExclusion()
            guard !devices.isEmpty else { return "" }

            let rendered = devices.map { "    \"\($0)\"" }.joined(separator: "\n")
            AppLogger.shared.log("🧩 [KanataConfig] Excluding macOS devices from interception: \(devices.joined(separator: ", "))")
            return """

          ;; Avoid grabbing VirtualHID output keyboard(s); prevents feedback loops.
          macos-dev-names-exclude (
        \(rendered)
          )
        """
        #else
            return ""
        #endif
    }

    #if os(macOS)
        private static func detectMacOSVirtualHIDDevicesForExclusion() -> [String] {
            guard let output = runKanataListForDeviceNames() else { return [] }

            // Example lines (columns):
            // 0xHASH   vendor_id  product_id  product_key...
            // We exclude both the hash and the product key for robustness.
            let re = try? NSRegularExpression(pattern: #"^(0x[0-9A-Fa-f]+)\s+\d+\s+\d+\s+(.*)$"#)
            var results = Set<String>()

            for rawLine in output.split(separator: "\n", omittingEmptySubsequences: false) {
                let line = rawLine.trimmingCharacters(in: .whitespacesAndNewlines)
                guard !line.isEmpty else { continue }
                guard line.contains("VirtualHIDKeyboard") || line.contains("VirtualHID") else { continue }
                guard let re else { continue }

                let ns = line as NSString
                let range = NSRange(location: 0, length: ns.length)
                guard let m = re.firstMatch(in: line, range: range) else { continue }
                guard m.numberOfRanges >= 3 else { continue }

                let hash = ns.substring(with: m.range(at: 1)).trimmingCharacters(in: .whitespaces)
                let productKey = ns.substring(with: m.range(at: 2)).trimmingCharacters(in: .whitespaces)

                if !hash.isEmpty { results.insert(hash) }
                if !productKey.isEmpty { results.insert(productKey) }
            }

            return results.sorted()
        }

        private static func runKanataListForDeviceNames() -> String? {
            // Prefer the canonical system install path (stable TCC identity).
            let candidates = [
                "/Library/KeyPath/bin/kanata",
                "/Applications/KeyPath.app/Contents/Library/KeyPath/kanata"
            ]

            let fm = FileManager.default
            guard let kanataPath = candidates.first(where: { fm.isExecutableFile(atPath: $0) }) else {
                return nil
            }

            do {
                let process = Process()
                process.executableURL = URL(fileURLWithPath: kanataPath)
                process.arguments = ["--list"]

                let pipe = Pipe()
                process.standardOutput = pipe
                process.standardError = pipe

                try process.run()
                process.waitUntilExit()

                let data = pipe.fileHandleForReading.readDataToEndOfFile()
                guard process.terminationStatus == 0 else { return nil }
                return String(data: data, encoding: .utf8)
            } catch {
                AppLogger.shared.warn("⚠️ [KanataConfig] Failed to run kanata --list for device detection: \(error)")
                return nil
            }
        }
    #endif
}
